# optional. 配置文件 title optional
title = "数据导入样例"
# optional. 是否自动创建所配置的DB和超级表, true|false, 默认 true. 同命令行参数 auto-create，但优先级低于命令行,
auto_create = true
# optional. 结果输出的目标文件，同命令行参数 output-file，但优先级低于命令行
output_file = ""
# optional. 导入数据所在路径。
# 如果指定该参数，则所有文件名相关的配置如果不是绝对路径的话即在该目录下以相对路径进行搜索。
# 如果未指定该参数，则所有文件名相关的配置必须为绝对路径。
data_dir = "/Users/sunpeng/workspace/tmp/taos/data"
# optional. 数据文件名后缀，仅在指定了 data_dir 时有效。此时要处理的文件集合为 data_dir 下符合后缀名规则的所有文件。
# 在 data_dir 设置的情况下，data_files 和 file_suffix 互斥，二者只可取其一。
# 在 data_dir 未设置的情况下，file_suffix 被忽略，设置无效。
data_file_suffix = ".csv"
# optional. 数据文件列表。
# 如果指定了 data_dir，该参数可以为空，此时表示 data_dir 下所有文件或者符合匹配规则的文件 。
# 如果指定了 data_dir ，该参数可以是一个混合了绝对路径和相对目录的文件名列表，形如 ["a.csv", "b.csv", "c.csv", "/tmp/x.csv"]
# 如果未指定 data_dir ，则 data_files 是一个强制存在的参数，其指定了一个由绝对路径名构成的 文件列表 ["/tmp/a.csv", "/tmp/b.csv"]
#data_files = ["/tmp/data/a.csv", "/tmp/data/b.csv"] # 数据文件列表
# optional. 指定 tag 的文件所在的目录。其含义及使用规则类似 data_dir
#tags_dir = ""
# optional. 指定 tag 的文件名后缀。其含义及使用规则类似  data_file_suffix
#tags_file_suffix = ""
# optional. 指定 tag 的文件列表。其含义及使用规则类似 data_files
tags_files = ["/Users/sunpeng/workspace/tmp/taos/tag/tag.csv"]
# optional. 每批写入的记录数。
batch_size = 10
# 最大并发处理
concurrent = 1

[tdengine]
# Required. tdengine host
host = "localhost"
# Required. tdengine port
port = 6030
# Required. tdengine user
user = "root"
# Required. tdengine password
password = "taosdata"

[db]
# db name
name = "test"
# optional。一个 VNODE 写入内存池大小，单位为 MB，默认为 96。 请参考 https://docs.taosdata.com/taos-sql/database/
buffer = 96
# optional。否在内存中缓存子表的最近数据。默认为 none，其他可选值有last_row｜last_value｜both。请参考 https://docs.taosdata.com/taos-sql/database/
cache_model = "none"
# optional。每个 vnode 中用于缓存子表最近数据的内存大小。默认为 1 ，范围是[1, 65536]，单位是 MB。请参考 https://docs.taosdata.com/taos-sql/database/
cache_size = 1
# optional。数据文件存储数据的时间跨度，请参考 https://docs.taosdata.com/taos-sql/database/
duration = "10d"
# optional。表示数据文件保存的天数，缺省值为 3650，取值范围 [1, 365000]，且必须大于或等于 DURATION 参数值。 请参考 https://docs.taosdata.com/taos-sql/database/
keep = 3650
# optional。数据库的时间戳精度，taos_importer 默认 us。 请参考 https://docs.taosdata.com/taos-sql/database/
precision = "us"
# optional。DB中vgroup的数量，请参考 https://docs.taosdata.com/taos-sql/database/
vgrooups = 1

[stable]
# Required。超级表 name
name = "t_stock_detail_date_l2_transaction"
# Optional。表名模版，比如 t_{code}_{name}，如果不指定，则取所有 tag 的 hash
child_table_name_prefix = "t_"
child_table_name = "contact(\"t_\", sub_str(S_INFO_WINDCODE, 1, index_of(S_INFO_WINDCODE, \".\")))" # optional

# 超级表 column，类型为 column 数组
[[stable.columns]]
# required。列名
field = "ts"
# required。类型
type = "timestamp"
# required。数据来源，支持表达式，即从源数据文件中的列到 TDengine 中的目标列的映射关系。
source = "avoid_datetime_conflict(date_parse(date + left_pad(time, \"0\", 9), \"YYYYMMDDHHmmssSSS\"), 1000)"

[[stable.columns]]
field = "code"
type = "int"
source = "code"

[[stable.columns]]
filed = "wind_code"
type = "varchar(10)"
source = "wind_code"

[[stable.columns]]
field = "name"
type = "nchar(20)"
source = "name"

[[stable.columns]]
field = "function_code"
type = "int"
source = "function_code"

[[stable.columns]]
field = "order_kind"
type = "int"
source = "order_kind"

[[stable.columns]]
field = "bs_flag"
type = "int"
source = "bs_flag"

[[stable.columns]]
field = "trade_price"
type = "int"
source = "trade_price"

[[stable.columns]]
field = "trade_volume"
type = "int"
source = "trade_volume"

[[stable.columns]]
field = "ask_order"
type = "int"
source = "ask_order"

[[stable.columns]]
field = "bid_order"
type = "int"
source = "int"

[[stable.columns]]
field = "channel"
type = "int"
source = "channel"

[[stable.columns]]
field = "index"
type = "int"
source = "index"

[[stable.columns]]
field = "biz_index"
type = "int"
source = "biz_index"

# 超级表 tag，类型为 column 数组
[[stable.tags]]
field = "OBJECT_ID"
type = "nchar(50)"
source = "OBJECT_ID"

[[stable.tags]]
field = "S_INFO_WINDCODE"
type = "varchar(10)"
source = "S_INFO_WINDCODE"

[[stable.tags]]
field = "S_INFO_CODE"
type = "varchar(10)"
source = "S_INFO_CODE"

[[stable.tags]]
field = "S_INFO_NAME"
type = "nchar(10)"
source = "S_INFO_NAME"

[[stable.tags]]
field = "S_INFO_COMPNAME"
type = "nchar(20)"
source = "S_INFO_COMPNAME"

[[stable.tags]]
field = "S_INFO_COMPNAMEENG"
type = "varchar(100)"
source = "S_INFO_COMPNAMEENG"

[[stable.tags]]
field = "S_INFO_ISINCODE"
type = "varchar(20)"
source = "S_INFO_ISINCODE"

[[stable.tags]]
field = "S_INFO_EXCHMARKET"
type = "nchar(20)"
source = "S_INFO_EXCHMARKET"

[[stable.tags]]
field = "S_INFO_LISTBOARD"
type = "nchar(20)"
source = "S_INFO_LISTBOARD"

[[stable.tags]]
field = "S_INFO_LISTDATE"
type = "varchar(20)"
source = "S_INFO_LISTDATE"

[[stable.tags]]
field = "S_INFO_DELISTDATE"
type = "varchar(20)"
source = "S_INFO_DELISTDATE"

[[stable.tags]]
field = "S_INFO_SEDOLCODE"
type = "nchar(20)"
source = "S_INFO_SEDOLCODE"

[[stable.tags]]
field = "CRNCY_CODE"
type = "nchar(20)"
source = "CRNCY_CODE"

[[stable.tags]]
field = "S_INFO_PINYIN"
type = "nchar(20)"
source = "S_INFO_PINYIN"

[[stable.tags]]
field = "S_INFO_LISTBOARDNAME"
type = "nchar(20)"
source = "S_INFO_LISTBOARDNAME"

[[stable.tags]]
field = "IS_SHSC"
type = "nchar(2)"
source = "IS_SHSC"

[[stable.tags]]
field = "S_INFO_COMPCODE"
type = "varchar(10)"
source = "S_INFO_COMPCODE"

[[stable.tags]]
field = "OPDATE"
type = "nchar(20)"
source = "OPDATE"

[[stable.tags]]
field = "OPMODE"
type = "nchar(20)"
source = "OPMODE"
